### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by quo91** [ForbesLindesay/sync-rpc#4] opened 2019-01-16 20:02 UTC
So I get an error pointing me to this part of the code:
```
function httpGet(url){
  var response = request(
	'GET',
	url, (err, res, body) => {
		if(err)
		{
			return console.dir(err);
		}
	});
	return response.body;
}
```

The error says this:
C:\Users\CP\Desktop\BitBot\node_modules\sync-rpc\lib\index.js:130
      throw new Error(
      ^

Error: nodeNC failed:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:622:25)

    at sendMessage (C:\Users\CP\Desktop\BitBot\node_modules\sync-rpc\lib\index.js:130:13)
    at C:\Users\CP\Desktop\BitBot\node_modules\sync-rpc\lib\index.js:159:25
    at request (C:\Users\CP\Desktop\BitBot\node_modules\sync-request\lib\index.js:28:15)
    at httpGet (C:\Users\CP\Desktop\BitBot\test.js:229:27)
    at GetPrice (C:\Users\CP\Desktop\BitBot\test.js:197:25)
    at Request.get [as _callback] (C:\Users\CP\Desktop\BitBot\test.js:178:21)
    at Request.self.callback (C:\Users\CP\Desktop\BitBot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\CP\Desktop\BitBot\node_modules\request\request.js:1161:10)

**Comment by ForbesLindesay** [comment] 2019-01-22 17:03
This looks like a duplicate of #3

**Closed as completed by ForbesLindesay** 2019-01-22 17:03 UTC
